config/routes.rb
Surfipedia::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
  end

  authenticated :user do
    root to: 'wikis#index', as: 'authenticated_root'
  end
  
  resources :wikis do
    resources :collaborators
  end

  resources :charges, only: [:new, :create]

  get '/wikis/public', to: 'wikis#public'
  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

  validates :user_id, uniqueness: { scope: :wiki_id }
  
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_collaborator, only: [:show, :edit, :update, :destroy]
  before_action :set_wiki, only: [:new, :create, :index]
  
  def index
    @collaborators = @wiki.collaborators
  end

  def show
    @users = User.all
  end

  def new
    @users = User.find(current_user.id)
    @collaborator = @wiki.collaborators.new
  end

  def edit
  end

  def create
    @collaborator = @wiki.collaborators.build(collaborator_params)
    
    respond_to do |format|
      if @collaborator.save
        format.html { redirect_to @wiki, notice: 'Successfully added collaborators' }
        format.json { render :show, status: :created, location: @collaborator }
      else
        format.html { render :new }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @collaboration.destroy
        format.html { redirect_to collaborators_url, notice: "Collaboration was removed." }
        format.json { head :no_content}
      else
        flash[:error] = "Collaboration couldn't be removed. Try again."
      end
    end
  end

  def update
    respond_to do |format|
      if @collaborator.update(collaborator_params)
        format.html { redirect_to @collaborator, notice: 'Collaborators was successfully updated' }
        format.json { render :show, status: :ok, location: @collaborator }
      else
        format.html { render :edit }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def set_collaborator
    @collaborator = Collaborator.find(params[:id])
  end

  def set_wiki
    @wiki = Wiki.friendly.find(params[:wiki_id])
  end

  def collaborator_params
    params.require(:collaborator).permit(:user_id, :wiki_id)
  end
end

app/views/collaborators/_form.html.erb
<%= form_for([@wiki, @collaborator]) do |f| %>
  <% if @collaborator.errors.any? %>
    <div id="error_explanation">
      <% render 'shared/error_messages', object: f.object %>
      <h2><%= pluralize(@collaborator.errors.count, "error") %> prohibited this collaborator from being saved: </h2>
        <ul>
          <% @collaborator.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div>
    <%= f.select :user_id, options_for_select( User.all.map { |u| [u.username, u.id] }), { :include_blank => "-- Select One --" } %>
  </div>
  <br/>

  <%= f.submit "Update", class: 'btn btn-success' %>
<% end %>

app/views/collaborators/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Updating Collaborator</h1>
  
      <%= render 'form' %>

  </div>
</div>

app/views/collaborators/index.html.erb
<h1><%= @wiki.title %> collaborators</h1>

<table>
  <thead>
    <tr>
      <th>Users:</th>
    </tr>
  </thead>

  <tbody>
    <% @collaborators.each do |collaborator| %>
      <tr>
        <td><%= collaborator.user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collaborator', new_wiki_collaborator_path %>

app/views/collaborators/new.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>New Collaborator</h1>

      <%= render 'form' %>
  </div>
</div>

app/views/collaborators/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <strong>User:</strong>
  <%= @collaborator.user %>
</p>

<p>
  <strong>Wiki:</strong>
  <%= @collaborator.wiki %>
</p>

<%= link_to 'Edit', edit_collaborator_path(@collaborator) %>