config/routes.rb
Surfipedia::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
  end

  authenticated :user do
    root to: 'wikis#index', as: 'authenticated_root'
  end
  
  resources :wikis do
    resources :collaborators
  end

  resources :charges, only: [:new, :create]

  get '/wikis/public', to: 'wikis#public'
  root to: 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true, length: { minimum: 20 }

  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  def index
    @wikis = current_user.wikis
    @wikis = Wiki.paginate(page: params[:page], per_page: 15)
    @collaborations = current_user.collaborations
  end

  def public
    @wikis = Wiki.where('private = ?', false)
  end

  def show
  end

  def new
    @wiki = current_user.wikis.build
  end

  def create
    @wiki = current_user.wikis.new(wikis_params)

    respond_to do |format|              
      if @wiki.save
        format.html { redirect_to @wiki, notice: "Wiki created." }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])

    respond_to do |format|
      if @wiki.update(wikis_params)
          format.html { redirect_to @wiki, notice: "Wiki was updated" }
          format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])

    respond_to do |format|
      if @wiki.destroy
        format.html { redirect_to wikis_url, notice: "Wiki was successfully deleted." }
        format.json { head :no_content }
      else
        flash[:error] = "There was an error deleting wiki. Please try again."
        render :show
      end
    end
  end

private
  def set_wiki
    @wiki = Wiki.friendly.find(params[:id])
  end

  def wikis_params
    params.require(:wiki).permit(:title, :body, :private, :user_id)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <% render 'shared/error_messages', object: f.object %>
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved: </h2>
        <ul>
          <% @wiki.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>

        
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, id: "epictextarea", class: 'hide', placeholder: "Enter wiki body" %>

        <div id="epiceditor" class="form-control">
        </div>

        <% if @wiki.user == current_user %>
          <div class="form-group">
            <%= f.label :private %><br>
            <%= f.check_box :private %>
          </div>
        <% end %>
      
      <%= f.submit "Update", class: 'btn btn-success' %>

<% end %>

app/views/wikis/edit.html.erb
<div class="row">
 
  <div class="col-md-8">
    <h1>Edit Wiki</h1>

    <%= render 'form' %>  
  </div>

  <% if current_user.premium? && @wiki.user == current_user %>
    <%= link_to 'Add Collaborator', new_wiki_collaborator_path(@wiki) %>
  <% end %>

</div>

app/views/wikis/index.html.erb
<h2>My Wikis</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th colspan="<%= @colspan %>"></th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= wiki.created_at %></td>
        <td><%= wiki.updated_at %></td>
        <% if current_user %>
          <td><%= link_to 'View Collaborators', wiki_collaborators_path(wiki) %></td>
          <td><%= link_to 'Add Collaborator', new_wiki_collaborator_path(wiki) %></td>
        <% end %>

        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Delete', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Wikis Shared with me</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created By</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @collaborations.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= wiki.user.username %></td>
        <td><%= wiki.created_at %></td>
        <td><%= wiki.updated_at %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/new.html.erb
<%= provide(:title, 'New Wiki') %>
  <div class="row">
   
    <div class="col-md-8">
      <h1>New Wiki</h1>

      <%= render 'form' %>
    </div>
  </div>

app/views/wikis/public.html.erb
<div class="row">
  <div class="col-md-8">
    <h1> Public Wikis</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Created By</th>
          <th>Date Created</th>
          <th>Last Updated</th>
        </tr>
      </thead>
      
      <tbody>
        <% @wikis.each do |wiki| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
              <tr>
                <td><%= link_to wiki.name, wiki_path(wiki) %></td>
                <td><%= wiki.user.name %></td>
                <td><%= wiki.created_at %></td>
                <td><%= wiki.updated_at %></td>
              </tr>
            </div>
          </div>
        <% end %>
      </tbody> 
    </table>
    <%= will_paginate @wikis %>
  </div>

  <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="col-md-8">
    <div class="page-header">
      <h1><%= markdown @wiki.title %></h1>
      <% if @wiki.user == current_user %> 
        <h4 style="display:inline; vertical-align:middle;"><%= @wiki.user.username %></h4>
        <%= link_to 'Edit', edit_wiki_path(@wiki), class: 'btn btn-sm btn-default' %>
        <%= link_to 'Delete', wiki_path(@wiki), method: :delete, class: 'btn btn-sm btn-danger' %>
      <% end %>
      
    </div>
    <%= markdown @wiki.body %>
  </div>

<br/>
 