config/routes.rb
Surfipedia::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
  end

  authenticated :user do
    root to: 'wikis#index', as: 'authenticated_root'
  end
  
  resources :wikis do
    resources :collaborators
  end

  resources :charges, only: [:new, :create]

  get '/wikis/public', to: 'wikis#public'
  root to: 'welcome#index'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    @amount = 2500

    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
   
    # Where the real magic happens
    begin
      charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in the app
        amount: @amount,
        description: "Blocipedia Membership = #{current_user.email}",
        currency: 'usd'
      )

      if current_user.update(premium: true)
        flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
        redirect_to edit_user_registration_path
      else
        flash[:success] = "There was an error upgrading your account. Please contact support!"
        redirect_to edit_user_registration_path
      end

      # Stripe will send back CardErrors, with friendly messages
      # when something goes wrong.
      # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
  end

  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     email: current_user.email,
     description: "Blocipedia Membership - #{current_user.username}",
     amount: 2500
    }
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <!-- The form doesn't pass the amount to the create action, so we have to pass it manually. -->
  <%= hidden_field_tag :amount, @stripe_btn_data[:amount] %>

  <h4>Click the button!</h4>
  <script 
    class='stripe-button' 
    src="https://checkout.stripe.com/checkout.js" 
    data-key="<%= @stripe_btn_data[:key] %>" 
    data-amount="<%= @stripe_btn_data[:amount] %>"
    data-name="Blocipedia"
    data-description="One Year Membership"
    data-email="<%= @stripe_btn_data[:email] %>" >
  </script>
<% end %>